spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    br.com.ikonbrasil.cadastrofiliados: INFO
    org.flywaydb: INFO
