spring:
  application:
    name: ms-cadastro-filiados
  profiles:
    active: dev
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
    create-schemas: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Microsservico de cadastro de filiados da IKO Nakamura Brasil
    version: 0.0.1-SNAPSHOT

ikon:
  auth:
    jwt-secret: ${JWT_SECRET:ikon-auth-dev-secret-change-me-ikon-auth-dev-secret-change-me}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
